#root@db-gb:/home/db# cat 01-network-manager-all.yaml 
# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager

#root@db-gb:/home/db# cat 02-dhcp-networkd.yaml 
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: yes
      dhcp4-overrides:
        use-dns: no
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

#root@db-gb:/home/db# cat 03-static-networkd.yaml 
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [192.168.1.80/24]
      routes:
        - to: default
          via: 192.168.0.254
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

